#Brief: Makefile for IVS project
#Project: Calculator
#University: BUT FIT
#Author: Stanislav Gabriš <xgabri18(at)fit.vutbr.cz>
AUTHORS=xorsza01_xgabri18_xvlkja07_xjarol06


all:
	
pack:
	#tar...
clean:
	#rm...
test:
	python3 -m unittest tests.TestBaseOperations tests.TestAdvancedOperations

doc:
	#doxy...?
run:
	#
profile:
	#
